baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'StackGrandiose'
theme = 'agile'

[markup.goldmark.parser.attribute] #https://roneo.org/en/hugo-custom-css-classes-images-markdown-attributes/
block = true
title = true 

[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files
