name = "XMin"
license = "MIT"
licenselink = "https://github.com/yihui/hugo-xmin/blob/master/LICENSE.md"
description = "Theme forked from Yihui Xie's XMin Hugo theme"
homepage = "https://xmin.yihui.org"
tags = ["minimal", "blog", "personal", "clean", "simple", "starter", "minimalist"]
features = ["blog"]
min_version = "0.18"

[author]
  name = "Yihui Xie"
  homepage = "https://yihui.org"
